### ISSUE TITLE
BigQuery template has dataset/table race condition

### ISSUE THREAD

**Issue by bohdanyurov-gl** [GoogleCloudPlatform/cloud-foundation-toolkit#127]
Creating dataset & tables in a single run has a high chance for "dataset not found error" to occur.

dependsOn does not help

**Comment by duizendstra** [comment]
Based on the code and the test file I concluded that the dependsOn should be in the properties as:
```
    properties:
      name: test_bq_table
      dependsOn:
        - test-bq-dataset
```
The documentation mentions that dependsOn should be added as [metadata](https://cloud.google.com/deployment-manager/docs/configuration/create-explicit-dependencies#creating_dependencies). 

Adding it to the properties as shown above does get rid of the race condition, however, it seems wrong to add it to the properties
