### ISSUE TITLE
Can not remove mid list members from iam_member type

### ISSUE THREAD

**Issue by marko7460** [GoogleCloudPlatform/cloud-foundation-toolkit#151]
1. Create deployment with this manifest:
```
imports:
  - path: templates/iam_member/iam_member.py
    name: iam_member.py

resources:
  - name: roles-app-sa
    type: iam_member.py
    properties:
      projectId: my-project-id
      roles:
        - role: roles/bigquery.jobUser
          members:
            - serviceAccount:sa-0@my-project-id.iam.gserviceaccount.com
            - serviceAccount:sa-1@my-project-id.iam.gserviceaccount.com
            - serviceAccount:sa-2@my-project-id.iam.gserviceaccount.com
            - serviceAccount:sa-3@my-project-id.iam.gserviceaccount.com
```
2. Remove `serviceAccount:sa-2@my-project-id.iam.gserviceaccount.com` and run update
```
imports:
  - path: templates/iam_member/iam_member.py
    name: iam_member.py

resources:
  - name: roles-app-sa
    type: iam_member.py
    properties:
      projectId: my-project-id
      roles:
        - role: roles/bigquery.jobUser
          members:
            - serviceAccount:sa-0@my-project-id.iam.gserviceaccount.com
            - serviceAccount:sa-1@my-project-id.iam.gserviceaccount.com
            - serviceAccount:sa-3@my-project-id.iam.gserviceaccount.com
```

You will get the following error:
```
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1560956113370-58bae6aa5bc86-d0af0e60-3c537b39]: errors:
- code: NO_METHOD_TO_UPDATE_FIELD
  message: No method found to update field 'member' on resource 'get-iam-policy-addroles-app-sa-0-2'
    of type 'cloudresourcemanager-v1'. The resource may need to be recreated with
    the new field.
```

We can only remove members from the bottom of the list, not in the middle of the list. If i remove ` serviceAccount:sa-3@my-project-id.iam.gserviceaccount.com` and ` serviceAccount:sa-2@my-project-id.iam.gserviceaccount.com` the deployment will be updated without problems.
