### ISSUE TITLE
Invalid example for backend service

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#272]
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/b6cf171597861707ddeeba7ae852bc3b42f9dab0/dm/templates/backend_service/examples/backend_service_global.yaml#L18

Missing mandatory properties:

```
 loadBalancingScheme:
    enum: ["EXTERNAL"]
 sessionAffinity:
     enum:
         - NONE
         - CLIENT_IP
         - GENERATED_COOKIE
```

```
dataPath: '.protocol',
schemaPath: '#/allOf/1/oneOf/0/allOf/0/properties/protocol/enum',
params: { allowedValues: [Object] },
message: 'should be equal to one of the allowed values' },
{ keyword: 'required',
dataPath: '',
schemaPath: '#/allOf/1/oneOf/1/allOf/1/required',
params: { missingProperty: '.portName' },
message: 'should have required property \'.portName\'' },
{ keyword: 'oneOf',
dataPath: '',
schemaPath: '#/allOf/1/oneOf',
params: { passingSchemas: null },
message: 'should match exactly one schema in oneOf' } ]
```
