### ISSUE TITLE
DM/CLI Could not  resolve cross-deployment reference in case of hierarchical resource outputs

### ISSUE THREAD

**Issue by kopachevsky** [GoogleCloudPlatform/cloud-foundation-toolkit#333]
```
2019/09/14 23:36:12 gcloud deployment-manager deployments describe act-cft-folders --project cft-test-workspace-221111 --format yaml
2019/09/14 23:36:13 failed to start cmd: exit status 1, output: ERROR: (gcloud.deployment-manager.deployments.describe) ResponseError: code=404, message=The object 'projects/cft-test-workspace-221111/global/deployments/act-cft-folders' is not found.
```

It looks like during cft apply you are doing a describe even if the deplyoment is not existing, which fails

Files to reproduce

```
folder-cft.yaml
------------------------------------------------------------------------------------------------
name: act-cft-folders
project: cft-test-workspace-221111

imports:
- path: ../../templates/folder/folder.py
  name: custom-folder.py

resources:
- name: org-cft-folder
  type: custom-folder.py
  properties:
    folders:
      - name: act-cft-root
        orgId: organizations/518838582041
        displayName: act under Organization
      - name: act-cft-dev
        folderId: $(ref.act-cft-root.name)
        displayName: act under Folder dev
      - name: act-cft-prod
        folderId: $(ref.act-cft-root.name)
        displayName: act under Folder prod

project-host-cft.yaml
---------------------------------
name: acc-cft-project-dev
project: cft-test-workspace-221111

imports:
- path: ../../templates/project/project.py
  name: project_custom.py

resources:
- name: cft-project
  type: project_custom.py
  properties:
    folders: $(out.act-cft-folders.org-cft-folder.folders)
    folderName: act-cft-dev
    properties:
      billingAccountId: 005E57-23E6CA-69A366
      projectId: acc-cft-dev-1
      parent:
        type: folder
      activateApis:
        - compute.googleapis.com
        - deploymentmanager.googleapis.com
      serviceAccounts:
        - accountId: cft-demo-sa-0
          displayName: cft demo service account 0
          roles:
            - roles/editor
            - roles/viewer
          networkAccess: true
      usageExportBucket: false
      sharedVPCHost: true
      removeDefaultVPC: true

```

**Comment by kopachevsky** [comment]
The issue is following, in certain cases deployment manifests outputs looks like this

```
layout: |
  resources:
  - name: org-cft-folder
    properties:
      folders:
      - displayName: act under Organization
        name: act-cft-root
        orgId: organizations/518838582041
        resourceNameSuffix: froot
      - displayName: act under Folder dev
        folderId: $(ref.org-cft-folder-froot.name)
        name: act-cft-dev
        resourceNameSuffix: fdev
      - displayName: act under Folder prod
        folderId: $(ref.org-cft-folder-froot.name)
        name: act-cft-prod
        resourceNameSuffix: fprod
    resources:
    - name: org-cft-folder
      outputs:
      - finalValue:
          org-cft-folder-fdev:
            createTime: '2019-09-29T17:30:45.613Z'
            displayName: act under Folder dev
            lifecycleState: ACTIVE
            name: folders/237656312840
            parent: folders/315320405251
          org-cft-folder-fprod:
            createTime: '2019-09-29T17:30:46.307Z'
            displayName: act under Folder prod
            lifecycleState: ACTIVE
            name: folders/894616298630
            parent: folders/315320405251
          org-cft-folder-froot:
            createTime: '2019-09-29T17:30:34.852Z'
            displayName: act under Organization
            lifecycleState: ACTIVE
            name: folders/315320405251
            parent: organizations/518838582041
        name: folders
```
As you can see **org-cft-folder** resource don't have outputs as it usually happens, but instead it has **resources** element with **org-cft-folder** resource that HAS outputs. This is quite rare case was hard to identify, fix would be to iterate over ALL inner **resources** elements and take resources with not empty **outputs**
