### ISSUE TITLE
[CFT Scorecard] Add `target` and `exclude` filtering

### ISSUE THREAD

**Issue by ocervell** [GoogleCloudPlatform/cloud-foundation-toolkit#336]
Currently, the `target` and `exclude` fields are not correctly picked up by CFT Scorecard.

For instance, the following rule works and returns 6 violations in my env:

```
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPExternalIpAccessConstraintV1
metadata:
  name: compute_org_found_public_ip
spec:
  severity: high
#  match:
#    target: ["organization/103912657018"]
#    exclude: []
  parameters:
    mode: whitelist
    instances:
    - //compute.googleapis.com/projects/blabla/zones/us-east1-b/instances/blalba
```

but, when trying to uncomment the `target` / `match` fields, it returns no violations.

I believe we need to implement the `getAncestryPath` [function](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/cli/scorecard/violations.go#L117) that currently returns a dummy value.
