### ISSUE TITLE
Schema validation is too complex

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#360]
The 3rd part is not needed. OneOf (a,b) already blocks having a AND b.

```
  - oneOf:
      - required:
          - healthCheck
      - required:
          - healthChecks
      - allOf:
          - not:
              required:
                - healthCheck
          - not:
              required:
                - healthChecks
```

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/20d235a4636fc502c5534eb51cf81f43301d3422/dm/templates/backend_service/backend_service.py.schema#L40
