### ISSUE TITLE
Yaml string "on" / "off" is interpreted as boolean

### ISSUE THREAD

**Issue by frits-v** [GoogleCloudPlatform/cloud-foundation-toolkit#417]
I encounter this when using the `cloud_sql` template from the master branch. When specifying `databaseFlag`, value needs to be either on/off. Unquoted, these are boolean values in yaml, but quoted they should be strings. When running `cft` the values are cast to boolean somewhere though.
Example template:
```
# Example of the Cloud SQL template usage.

imports:
  - path: templates/cloud_sql/cloud_sql.py
    name: cloud_sql.py

resources:
  - name: cloud-sql-instance
    type: cloud_sql.py
    properties:
      region: us-central1
      settings:
        databaseFlags:
          - name: innodb_strict_mode
            value: 'off'
        tier: db-n1-standard-1
        backupConfiguration:
          startTime: '02:00'
          enabled: true
          binaryLogEnabled: true
        locationPreference:
          zone: us-central1-c
      users:
        - name: user-1
          host: 10.1.1.1
        - name: user-2
          host: 10.1.1.2
      databases:
        - name: db-1
        - name: db-2
```
Output:
```
googlecloudsdk.api_lib.deployment_manager.exceptions.OperationError: Error in Operation [
]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/000/manifests/manifest-0000110929
  message: |-
    Manifest expansion encountered the following errors: Invalid properties for 'cloud_sql.py':
    False is not of type 'string' at ['settings', 'databaseFlags', 0, 'value']
     Resource: 000 Resource: config

```
