### ISSUE TITLE
Log sink and pub/sub topic not working when created in different projects

### ISSUE THREAD

**Issue by tcprbs** [GoogleCloudPlatform/cloud-foundation-toolkit#431]
This is the same issue as [issue reported in old repo](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/505). 

**Problem**
In GCP console, when a log sink export is created, there is a way to choose custom destination where the destination can be a Pub/Sub topic in another project.

However, replicating the setup in deployment manager using logsink templates, does **not** create the pubsub in different project. 

It only shows the configuration values as different project. Deploying them still creates everything in DM project. 

**Configuration**
I tried using the project and projectId properties with another project ID but still it creates the sink and the pub/sub topic in the same DM project.

```
resources:
- name: test-pubsub
  type: logsink.py
  properties:
    project: pubsub-project-id
    projectId: sink-project-id # This seems to be used for getting value for sink's parent property. 
    destinationName: pubsub-topic 
    destinationType: pubsub
    # Rest of the config below like pubsubProperties.

```
Expanded config in deployment manager for log sink shows:
```
 parent: sink-project-id  
 destination: pubsub.googleapis.com/projects/pubsub-project-id/topics/pubsub-topic 
```

Executed using: 
`gcloud deployment-manager deployments create deployment-logsink --project=sink-project-id --config=config.yaml`

I expected the pubsub topic to be created in **pubsub-project**. But it gets created in same DM project. Only the expanded config in DM UI shows different project values. 

Thanks for responding in the old issue. However it seems to happen in the new version of code as well.
