### ISSUE TITLE
Can't remove nodePool from GKE cluster

### ISSUE THREAD

**Issue by tobiasmcnulty** [GoogleCloudPlatform/cloud-foundation-toolkit#441]
I'm using the DM GKE examples in: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates/gke/examples

I was able to create a cluster, and later I added a second node pool to the same cluster, both of which worked fine. When I try to remove the original node pool, however, the command dies with this error:
```
$ gcloud deployment-manager deployments update staging --config=staging.yaml 
The fingerprint of the deployment is <snip>
Waiting for update [operation-<snip>]...failed.                                                                                 
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-<snip>]: errors:
- code: CONDITION_NOT_MET
  location: /deployments/staging/resources/my-cluster->$.properties->$.name
  message: |-
    InputMapping for field [name] for method [delete] could not be set from input, mapping was: [$.concat($.resource.properties.parent, "/clusters/", $.ifNull($.resource.properties.name, $.resource.name), "/nodePools/", $.getElement($.resource.previous.cluster.nodePools, $.matches[0], "name"))
    ], and evaluation context was:
    <snip>
    Error was:
    Missing property in path $['resource']['previous']['cluster']
```

I can delete it via the console, but then the deployment and the actual infrastructure are forever out of sync. Is there some way I can delete this node pool via DM?

If helpful, here is my full config, including both node pools. The node pool named `core` is the one I tried and failed to remove with DM / CFT.

```
imports:
  - path: cloud-foundation-toolkit/dm/templates/gke/gke.py
    name: gke.py

resources:
  # adapted from cloud-foundation-toolkit/dm/templates/gke/examples/gke_regional.yaml
  - name: my-cluster
    type: gke.py
    properties:
      region: us-east1
      cluster:
        name: my-cluster
        description: GKE cluster
        network: default
        subnetwork: default
        ipAllocationPolicy:
          useIpAliases: true
        nodePools:
          - name: core
            initialNodeCount: 1  # per zone
            autoscaling:
              enabled: true
              minNodeCount: 1
              maxNodeCount: 4
            management:
              autoUpgrade: true
              autoRepair: true
            config:
              machineType: n1-standard-1  # 4 GB RAM
              diskSizeGb: 40
              diskType: pd-standard  # or pd-ssd
              oauthScopes:
                - https://www.googleapis.com/auth/compute
                - https://www.googleapis.com/auth/devstorage.read_write
                - https://www.googleapis.com/auth/logging.write
                - https://www.googleapis.com/auth/monitoring
          - name: core2
            initialNodeCount: 1  # per zone
            autoscaling:
              enabled: true
              minNodeCount: 1
              maxNodeCount: 4
            management:
              autoUpgrade: true
              autoRepair: true
            config:
              machineType: g1-small  # 1.7 GB RAM
              diskSizeGb: 20
              diskType: pd-standard  # or pd-ssd
              oauthScopes:
                - https://www.googleapis.com/auth/compute
                - https://www.googleapis.com/auth/devstorage.read_write
                - https://www.googleapis.com/auth/logging.write
                - https://www.googleapis.com/auth/monitoring
        locations:
          - us-east1-c
          - us-east1-d
```
