### ISSUE TITLE
MANAGED ssl-certificate support 

### ISSUE THREAD

**Issue by frots** [GoogleCloudPlatform/cloud-foundation-toolkit#458]
The current template and gcp-type provider (beta) for ssl certificates does not support google managed certificates. We now have to use an insert action directly to the API which is far from ideal.

```
resources:
  - name: my-managed-certificate-resource
    action: "gcp-types/compute-beta:compute.sslCertificates.insert"
    metadata:
      runtimePolicy:
        - CREATE
    properties:
      name: my-certificate
      type: MANAGED
      managed:
        domains:
          - mydomain.tld
```

**Comment by ocsig** [comment]
Have you tried `type: "gcp-types/compute-beta:sslCertificates"`? 

It is able to create the certificate with the config you used ( with a valid domain).

**Comment by frots** [comment]
Unfortunately it does not accept the type argument.

**Comment by ocsig** [comment]
This is woring for me:

```yaml
resources:
  - name: my-managed-certificate-resource
    type: "gcp-types/compute-beta:sslCertificates"
    properties:
      name: my-certificate
      type: MANAGED
      managed:
        domains:
          - cft.tips
```
