### ISSUE TITLE
resourcePolicies support as a CFT template

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#459]
Support for resourcePolicies resource:
https://cloud.google.com/compute/docs/reference/rest/v1/resourcePolicies/insert

CFT template support including readme, schema, example(s), integration test.

**Comment by ocsig** [comment]
Working simple example:

```yaml
resources:
  - name: policy
    type: gcp-types/compute-v1:resourcePolicies
    properties:
      project: myproject
      name: mypolicy
      region: europe-west1
      description: test1
      snapshotSchedulePolicy:
        schedule:
            weeklySchedule:
                dayOfWeeks:
                - day: "MONDAY"
                  startTime: "00:00"
```
