### ISSUE TITLE
[DM] External_load_balancer template fails to destroy demployment

### ISSUE THREAD

**Issue by paulpalamarchuk** [GoogleCloudPlatform/cloud-foundation-toolkit#491]
Insufficient dependencies for correct destruction order in external LB template.
Deployment destruction error (last step in bats-test):  
```
http-elb-wcz8i2jg57-target: {"ResourceType":"gcp-types/compute-v1:targetHttpProxies","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"The target_http_proxy resource 'projects/.../global/targetHttpProxies/http-elb-name-wcz8i2jg57-target' is already being used by 'projects/.../global/forwardingRules/http-elb-name-wcz8i2jg57'","reason":"resourceInUseByAnotherResource"}],"message":"The target_http_proxy resource 'projects/.../global/targetHttpProxies/http-elb-name-wcz8i2jg57-target' is already being used by 'projects/.../global/forwardingRules/http-elb-name-wcz8i2jg57'","statusMessage":"Bad Request","requestPath":"https://compute.googleapis.com/compute/v1/projects/.../global/targetHttpProxies/http-elb-name-wcz8i2jg57-target","httpMethod":"DELETE"}}
test-https-elb-wcz8i2jg57-target: {"ResourceType":"gcp-types/compute-v1:targetHttpsProxies","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"The target_https_proxy resource 'projects/.../global/targetHttpsProxies/test-https-elb-wcz8i2jg57-target' is already being used by 'projects/.../global/forwardingRules/test-https-elb-wcz8i2jg57'","reason":"resourceInUseByAnotherResource"}],"message":"The target_https_proxy resource 'projects/.../global/targetHttpsProxies/test-https-elb-wcz8i2jg57-target' is already being used by 'projects/.../global/forwardingRules/test-https-elb-wcz8i2jg57'","statusMessage":"Bad Request","requestPath":"https://compute.googleapis.com/compute/v1/projects/.../global/targetHttpsProxies/test-https-elb-wcz8i2jg57-target","httpMethod":"DELETE"}}
test-ssl-elb-wcz8i2jg57-target: {"ResourceType":"gcp-types/compute-v1:targetSslProxies","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"The target_ssl_proxy resource 'projects/.../global/targetSslProxies/test-ssl-elb-wcz8i2jg57-target' is already being used by 'projects/.../global/forwardingRules/test-ssl-elb-wcz8i2jg57'","reason":"resourceInUseByAnotherResource"}],"message":"The target_ssl_proxy resource 'projects/.../global/targetSslProxies/test-ssl-elb-wcz8i2jg57-target' is already being used by 'projects/.../global/forwardingRules/test-ssl-elb-wcz8i2jg57'","statusMessage":"Bad Request","requestPath":"https://compute.googleapis.com/compute/v1/projects/.../global/targetSslProxies/test-ssl-elb-wcz8i2jg57-target","httpMethod":"DELETE"}}
```

**Comment by paulpalamarchuk** [comment]
After investigating, I've discovered that the issue is related to the `gcp-types/compute-v1:globalForwardingRules` type. Looks like it ignores dependency on TargetProxy.  I've tested with TargetHttpProxy, TargetHttpsProxy, TargetTcpProxy and TargetSslProxy. My test example:

```yaml
resources:
- name: test-tcp-elb-2131s12b3s-target
  properties:
    name: test-tcp-elb-2131s12b3s-target
    project: gl-pp-dm-tests
    proxyHeader: PROXY_V1
    service: https://www.googleapis.com/compute/v1/projects/gl-pp-dm-tests/global/backendServices/test-ssl-backend-service-2s12eklb3s
  type: gcp-types/compute-v1:targetTcpProxies
- name: test-tcp-elb-2131s12b3s-forwarding-rule
  properties:
    IPProtocol: TCP
    loadBalancingScheme: EXTERNAL
    name: test-ssl-elb-2131s12b3s
    portRange: 443
    project: gl-pp-dm-tests
    target: $(ref.test-tcp-elb-2131s12b3s-target.selfLink)
  type: gcp-types/compute-v1:globalForwardingRules
  metadata:
    dependsOn:
    - test-tcp-elb-2131s12b3s-target
```
