### ISSUE TITLE
cloud_sql.py returns 400

### ISSUE THREAD

**Issue by rick-pri** [GoogleCloudPlatform/cloud-foundation-toolkit#530]
With some very minor naming changes to fit this into our own codebase but this doesn't work as it is returning this error on the first run after the creation preview.

```
Waiting for update [operation-1578326201106-59b7ab48e8013-4ab7a06c-f57787da]...failed.                                                                                                                            
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1578326201106-59b7ab48e8013-4ab7a06c-f57787da]: errors:
- code: RESOURCE_ERROR
  location: /deployments/test-cloud-sql-deploy/resources/cloud-sql-user-1
  message: '{"ResourceType":"gcp-types/sqladmin-v1beta4:users","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Request
    contains an invalid argument.","status":"INVALID_ARGUMENT","statusMessage":"Bad
    Request","requestPath":"https://www.googleapis.com/sql/v1beta4/projects/<proj id>/instances/cloud-sql-postgres-instance/users","httpMethod":"POST"}}'
```

Using the `cloud_sql.py`, `cloud_sql.py.schema` and `cloud_sql_postgres.yaml` and deploying using deployment-manager.

**Comment by rick-pri** [comment]
Also, having pulled down the whole CFT repo and copying in the `cloud_sql_postgres.yaml` and running `cft apply test-cloud-sql.yaml --preview` I seemingly get the same issue.

**Comment by rick-pri** [comment]
This still doesn't work a month and a half later.

**Comment by morgante** [comment]
@ocsig Any ideas what's breaking here?

**Comment by ocsig** [comment]
@rick-pri Can you confirm what minor changes you made in the codebase? ( Did you changed the CFT template, Schema or only the YAML? Can you share the diff of those files?)

There are 2 tipps for debugging:

1.  Try to run the [bats test with your local codebase](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/dm/docs/template_dev_guide.md#running-bats-tests-with-docker-image):

```bash
# Build test dcocker image:

cd cloud-foundation-toolkit/dm
make cft-build-base-image

# Run test
# To run templates/instance/tests/integration/instance.bats file, run:

make cft-test-bats TEST=templates/instance/tests/integration/instance.bats
# Or, if you have config file not in ~/.cloud-foundation-tests.conf:

make cft-test-bats TEST=templates/instance/tests/integration/instance.bats 
 CLOUD_FOUNDATION_CONF=/conf/file/location.json
```

2. Find the actual API call what DM maked in the Audit Logs. ( Look for CloudSQL users. Inside that look for the payload. You will find multiple entries for the same call, one of them contains all the parameters which DM actually sends to the API and the API return.) The error says some of these parameters are invalid. Double check if you can manually do the same operation at the Rest API doc page or via curl.

I will try to help you if you can share your changes here.

**Comment by rick-pri** [comment]
So, I copied the file from `dm/templates/cloud_sql/examples/cloud_sql_postgres.yaml` to `dm/cloud_sql_postgres.yaml` and that's all I did after cloning this repo from `master`. I just tried to do the same again and this time it complains about the resource name as it seems to be taking it from the file name? (I just pulled from master again today to try to follow my own instructions again)

> "Invalid value for field 'resource.name': 'cloud_sql_postgres'.  Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?'",

Now, after changing the name of the file I get:

```
---------- Stage 1 ----------
Waiting for insert cloud-sql-postgres (fingerprint Gy7U2YYxSrGvY3xCh58mPQ==) [operation-1582201214284-59f00ed573493-0b70b34f-5afda9c6]...failed.                                                                  
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/cloud_foundation_toolkit/cli.py", line 138, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/cloud_foundation_toolkit/cli.py", line 134, in main
    execute(args)
  File "/usr/local/lib/python2.7/dist-packages/cloud_foundation_toolkit/actions.py", line 136, in execute
    method(**arguments)
  File "/usr/local/lib/python2.7/dist-packages/cloud_foundation_toolkit/deployment.py", line 735, in apply
    self.create()
  File "/usr/local/lib/python2.7/dist-packages/cloud_foundation_toolkit/deployment.py", line 546, in create
    self.wait(operation)
  File "/usr/local/lib/python2.7/dist-packages/cloud_foundation_toolkit/deployment.py", line 694, in wait
    base64.urlsafe_b64encode(self.current.fingerprint)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/deployment_manager/dm_write.py", line 128, in WaitForOperation
    operation_name, dm_util.RenderMessageAsYaml(operation.error)))
googlecloudsdk.api_lib.deployment_manager.exceptions.OperationError: Error in Operation [operation-1582201214284-59f00ed573493-0b70b34f-5afda9c6]: errors:
- code: RESOURCE_ERROR
  location: /deployments/cloud-sql-postgres/resources/cloud-sql-postgres-instance
  message: '{"ResourceType":"gcp-types/sqladmin-v1beta4:instances","ResourceErrorCode":"INTERNAL_ERROR","ResourceErrorMessage":null}'
```

This was the end point that failed`https://www.googleapis.com/sql/v1beta4/projects/sysadmin-playground/instances`.

Here's the diff of the changes to the yaml file:
```
      region: europe-west2				      |	      region: us-central1
          zone: europe-west2-a				      |	          zone: us-central1-c
```

Apparently I need to install docker for the bats stuff.

**Comment by rick-pri** [comment]
Okay, after manhandling docker I now get that I can run `make cft-test-bats TEST=templates/cloud_sql/tests/integration/cloud_sql.bats`.

I can see that you're not testing private networking it seems, which I'm planning on using, and also I don't want a publicly accessible IP address either.

**Comment by rick-pri** [comment]
Also, it doesn't seem that you test Postgres at all.  The plain non mysql .bats file is also testing mysql.  I will have a look at creating a postgres yaml and bats file at some point but I may be busy for the rest of the day.

**Comment by rick-pri** [comment]
I'll let you set this up yourself so that I don't compromise your configuration as you'll understand this stuff better than I do @ocsig, but I immediately started to get failures running the tests with postgres as the DB in the `europe-west2` region (I don't think that it's a region thing although I didn't retest with `us-central1`.

**Comment by ocsig** [comment]
Thank you for your deep investigation. Let try to reproduce your errors.
I have to admit I am not a Postgres expert but let me share my early findings:

The current example fails for postgres
```json
jsonPayload: {
  "absoluteUri": "https://www.googleapis.com/sql/v1beta4/projects/cft-test-workspace-221111/instances/cloud-sql-postgres-instance/users" ,
  "body": {
   "host": "10.1.1.1" ,
   "name": "user1"    
  }
}
```

For a currently unknown reason if I call the api manually I am getting a better error message, which helped me to find the issue:
```json
{
  "error": {
    "code": 400,
    "message": "Invalid request: Missing native user password for PostgreSQL instance.",
    "errors": [
      {
        "message": "Invalid request: Missing native user password for PostgreSQL instance.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

This means the following example is working:
```yaml
# Example of the Cloud SQL template usage.
# Note that Postgres instances use different instance types then MySQL instances

imports:
  - path: templates/cloud_sql/cloud_sql.py
    name: cloud_sql.py

resources:
  - name: cloud-sql-postgres-instance
    type: cloud_sql.py
    properties:
      region: us-central1
      databaseVersion: POSTGRES_9_6
      instanceType: CLOUD_SQL_INSTANCE
      settings:
        tier: db-f1-micro
        backupConfiguration:
          startTime: '02:00'
          enabled: true
        locationPreference:
          zone: us-central1-c
      users:
        - name: user-1
          host: 10.1.1.1
          password: dummy2
        - name: user-2
          host: 10.1.1.2
          password: dummy3
      databases:
        - name: db-1
        - name: db-2

```

I will try to find time to create a test for postgres as. Please let me know if this solved your issue or you still having problems with regions/zones?

**Comment by rick-pri** [comment]
Ah, that makes sense.  Although, is there a way to get the secrets out of secret manager rather than hardcoding them into the yaml file. :/

We have our own deployment manager configurations which we need to move over to `cft` at some point (we started our work on our own DM templates some 9 months before work even began on `cft`).

**Comment by ocsig** [comment]
This was long on my backlog to experiment with the GCP secretmanager API. I managed to make it partially work and access a secret from DM, but it is Base64 encoded. So we are not there yet but I am optimistic.
( Also the CFT development starter around 2 years ago under the DM-Samples repo.)

**Comment by ocsig** [comment]
I actually have some happy news for you. I will publish more details on the secretmanager but for now, I managed to make this work:
```
resources:
- name: testsecretv1
  action: cft-test-workspace-221111/secrets-beta:secretmanager.projects.secrets.versions.access
  properties:
    name: "projects/cft-test-workspace-221111/secrets/sqldb2/versions/1"

- name: cloud-sql-postgres-instance2
  type: cloud_sql.py
  properties:
    region: us-central1
    databaseVersion: POSTGRES_9_6
    instanceType: CLOUD_SQL_INSTANCE
    settings:
      tier: db-f1-micro
      backupConfiguration:
        startTime: '02:00'
        enabled: true
      locationPreference:
        zone: us-central1-c
    users:
      - name: user2
        password: $(ref.testsecretv1.payload.data.base64Decode())
    databases:
      - name: db-1
      - name: db-2
```

Important note, you need `configVersion: v1alpha` to use the `base64Decode()` function. Because of this, this solution is experimental.

This means DM does not record the secret as plain text, however it will be sent ot the API as clear text, so the Audit logs will contain the secret.

**Comment by rick-pri** [comment]
> This was long on my backlog to experiment with the GCP secretmanager API. I managed to make it partially work and access a secret from DM, but it is Base64 encoded. So we are not there yet but I am optimistic.

Nice, I'll have to keep an eye out for this.

> ( Also the CFT development starter around 2 years ago under the DM-Samples repo.)

We found the deployment-manager samples repo shortly after we started work.

**Comment by rick-pri** [comment]
> I actually have some happy news for you. I will publish more details on the secretmanager but for now, I managed to make this work:
> 
> ```
> resources:
> - name: testsecretv1
>   action: cft-test-workspace-221111/secrets-beta:secretmanager.projects.secrets.versions.access
>   properties:
>     name: "projects/cft-test-workspace-221111/secrets/sqldb2/versions/1"
> 
> - name: cloud-sql-postgres-instance2
>   type: cloud_sql.py
>   properties:
>     region: us-central1
>     databaseVersion: POSTGRES_9_6
>     instanceType: CLOUD_SQL_INSTANCE
>     settings:
>       tier: db-f1-micro
>       backupConfiguration:
>         startTime: '02:00'
>         enabled: true
>       locationPreference:
>         zone: us-central1-c
>     users:
>       - name: user2
>         password: $(ref.testsecretv1.payload.data.base64Decode())
>     databases:
>       - name: db-1
>       - name: db-2
> ```
> 
> Important note, you need `configVersion: v1alpha` to use the `base64Decode()` function. Because of this, this solution is experimental.
> 
> This means DM does not record the secret as plain text, however it will be sent ot the API as clear text, so the Audit logs will contain the secret.

Whilst not wholly ideal, if we sent it in plain text that would still be the case that it would show up in the audit logs right?  We would need something in the API that recognises that this is sensitive so doesn't include it in plain text in the audit logs I guess?  You'll likely know better how to pass this request on @ocsig

**Comment by ocsig** [comment]
I don't see any reasonable way to do this on the generic API level, only on the product level. Which means the cloudSQL team needs to integrate KMS or GCP secrets into their product to make it work.
This would still not solve the other side of the problem when you try to pass a secret via startup script ( not saying that it is a good practice.)

Also I've later realized DM later displays the password at one place on the UI unfortunately. But that is something which can be changed.

**Comment by matthias-baetens** [comment]
I'm running into a similar issue as described above - the template works for region: `us-central1`, but not for `region: europe-west2` - were you able to find a fix for this? @ocsig

**Comment by ocsig** [comment]
> Ah, that makes sense. Although, is there a way to get the secrets out of secret manager rather than hardcoding them into the yaml file. 😕
> 
> We have our own deployment manager configurations in a git repo which we need to move over to `cft` at some point (we started our work on our own DM templates some 9 months before work even began on `cft`) and even though it's a private repo we don't want to be storing this stuff(passwords) in plain text.
> 
> In puppet for example, we store passwords in eyaml(encrypted yaml) so anyone with access to our puppet-control repo doesn't automatically have access to the passwords/secret keys etc.

@rick-pri The deployment manager team released an update, from now on every value which is called `password` or `secret` will be redacted and will not show up in logs or DM portal.

@matthias-baetens Would you mind to give me your yaml so I can reproduce your error?

**Comment by matthias-baetens** [comment]
@ocsig of course, thanks for having a look at this.

This config is unsuccessful:
```
resources:
  - name: ai-data-1591783089
    type: cloud_sql.py
    properties:
      region: europe-west1
      # region: us-central1
      databaseVersion: POSTGRES_9_6
      instanceType: CLOUD_SQL_INSTANCE
      settings:
        tier: db-f1-micro
        backupConfiguration:
          startTime: "02:00"
          enabled: true
        locationPreference:
          zone: us-central1-c
      users:
        - name: user-1
          password: dummy2
        - name: user-2
          password: dummy3
      databases:
        - name: db-1
        - name: db-2
```
While this config is successful:
```
resources:
  - name: ai-data-1591783088
    type: cloud_sql.py
    properties:
      # region: europe-west1
      region: us-central1
      databaseVersion: POSTGRES_9_6
      instanceType: CLOUD_SQL_INSTANCE
      settings:
        tier: db-f1-micro
        backupConfiguration:
          startTime: "02:00"
          enabled: true
        locationPreference:
          zone: us-central1-c
      users:
        - name: user-1
          password: dummy2
        - name: user-2
          password: dummy3
      databases:
        - name: db-1
        - name: db-2
```

The only real change is the region parameter.
