### ISSUE TITLE
unable to split the folder id value in jinja file

### ISSUE THREAD

**Issue by SprintCT** [GoogleCloudPlatform/cloud-foundation-toolkit#563]
Hi Team,

I'm doing project factory automation in jinja file, However i faced issue while split the folder name and folder id from folder api. Please find the below steps for more details

step1: I have created a folder using below code and it is successfully created.

resources:
  - name: {{ properties['foldername'] }}
    type: gcp-types/cloudresourcemanager-v2:folders
    properties:
      {% if properties['isorg'] == "yes" %}
      parent: organizations/{{ properties['orgid'] }}
      {% else %}
      parent: folders/{{ properties['parentfolderid'] }}
      {% endif %}
      displayName: {{ properties['folderdisplayName'] }}

Step 2: once created i need the folder id to parse the value in parent->id of project.

- name: {{ properties['projectid'] }}
  type: gcp-types/cloudresourcemanager-v1:projects
  properties:
    projectId: {{ properties['projectid'] }}
    parent:
      type: folders
      id: $(ref.{{ properties['foldername'] }}.name).split('/')[1]

I'm getting error that above split command, it is not working. Kindly assist me how to split the above value>

Example:
Output of Inline reference value for newly created folder name is : core/123456789
I want to split foldername is core and folderid is 12345678 with above jinja file.

**Comment by davidebelloni** [comment]
Hi,
I've a similar issue with another resource : iap.projects.brands.identityAwareProxyClients.create (I've created a deploymentmanager.v2beta.typeProvider to use it)

It create  a IAP Client and doesn't return name with the oauth2ClientId, but with relative path: projects/<id>/brands/<brands>/identityAwareProxyClients/<oauth2ClientId>

```
  - name: iap-v1
    type: deploymentmanager.v2beta.typeProvider
    properties: 
      descriptorUrl: 'https://iap.googleapis.com/$discovery/rest?version=v1'
      options:
        inputMappings:
          - fieldName: Authorization
            location: HEADER
            value: >
              $.concat("Bearer ", $.googleOauth2AccessToken())

  - name: brand
    action: {{ env["project"] }}/iap-v1:iap.projects.brands.create
    properties:
      parent: projects/{{ env['project_number'] }}
      supportEmail: "iap@goog.it"
      applicationTitle: "Brand"
    metadata:
      dependsOn: 
      - iap-v1
      runtimePolicy:
      - CREATE

  - name: iap-client
    action: {{ env["project"] }}/iap-v1:iap.projects.brands.identityAwareProxyClients.create
    properties:
      parent: projects/{{ env['project_number'] }}/brands/{{ env['project_number'] }}
      displayName: "IAP"
    metadata:
      dependsOn: 
      - iap-v1
      - brand
      runtimePolicy:
      - CREATE

```
I want to reference oauth2ClientId in a BackendService, but I don't know how to reference only the last field of the output value

```
  - name: global-https-backend-service
    type: backend_service.py
    properties:
      protocol: HTTPS
      loadBalancingScheme: EXTERNAL
      sessionAffinity: CLIENT_IP
      backends:
        - group: $(ref.uig.selfLink)
          balancingMode: UTILIZATION
          maxUtilization: 0.8
      healthChecks:
        - $(ref.https-healthcheck.selfLink)
      portName: https
      iap:
        enabled: true
        oauth2ClientId: $(ref.iap-client.name)   # HERE THE ISSUE, I NEED SOMETHING LIKE .SPLIT("/")[-1]
        oauth2ClientSecret: $(ref.iap-client.secret)

```

Thanks
