### ISSUE TITLE
cloudbuild trigger example not working - schema correct ?

### ISSUE THREAD

**Issue by komasoftware** [GoogleCloudPlatform/cloud-foundation-toolkit#602]
Example seen here : https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/dm/templates/cloudbuild/examples/cloudbuild_trigger.yaml

When running, 2 error messages that the schema is not matching

- Additional properties are not allowed ('branchName' was unexpected) at ['triggerTemplate']
- Additional properties are not allowed ('buildTemplate' was unexpected)

```
gcloud deployment-manager deployments update test-deployment --config=cloudbuild_trigger.yaml
The fingerprint of the deployment is BX7Pi_Hx1Q1mSLyZENJkSw==
Waiting for update [operation-1583859384742-5a083000072ae-37b7726c-725af8b2]...failed.                                                                                         
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1583859384742-5a083000072ae-37b7726c-725af8b2]: errors:
- code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/firebase-tools-cloudbuilder/manifests/manifest-1583859384940
  message: |-
    Manifest expansion encountered the following errors: Invalid properties for 'trigger.py':
    Additional properties are not allowed ('branchName' was unexpected) at ['triggerTemplate']
    Additional properties are not allowed ('buildTemplate' was unexpected)
     Resource: mybuildtrigger Resource: config
```

**Comment by komasoftware** [comment]
is this syntax supported ? the interpretation seems to fail.
branchName is not accepted as parameter to triggerTemplate.
```
...
properties:
  triggerTemplate:
    type: object
    additionalProperties: false
    properties:
      revision:
        type: string
        oneOf:
          - "$ref": "#/definitions/branchName"
          - "$ref": "#/definitions/tagName"
          - "$ref": "#/definitions/commitSha"

definitions:
  commitSha:
    type: string
    description: Explicit commit SHA to build.
  branchName:
    type: string
    description: The name of the branch to build.
  tagName:
    type: string
    description: The name of the tag to build.
...
```
