### ISSUE TITLE
Tests: There's no multi disk instance test or example

### ISSUE THREAD

**Issue by rick-pri** [GoogleCloudPlatform/cloud-foundation-toolkit#607]
As there is no multi disk instance test or example schema I don't actually know if the template works for this particular use case.

Currently I'm getting errors with the following yaml (I have a non-CFT template for the subnet in the file providing the resource to link to.):
```
  - path: templates/cft-instance.py
    name: instance.py

  - name: ew2a-db-01
    type: instance.py
    properties:
      zone: 'europe-west2-a'
      diskImage: 'projects/freebsd-org-cloud-dev/global/images/freebsd-12-1-release-amd64'
      machineType: 'n2-standard-1'
      diskType: 'pd-ssd'
      networks:
        - network: 'primarysite-test'
          subnetwork: '$(ref.db.selfLink)'
      disks:
        - deviceName: 'ssd-1'
          initializeParams:
            diskName: 'ssd-1'
            diskSizeGb: 500
            diskType: 'pd-ssd'
          autoDelete: false
          boot: false
      tags:
        items:
          - 'grp-01'
```

At the moment I'm trying to understand the error output but wanted to highlight the lack of testing of this use case here.

```
- code: RESOURCE_ERROR
  location: /deployments/<deployment_name>/resources/ew2a-db-01
  message: "{
    "ResourceType": "gcp-types/compute-v1:instances",
    "ResourceErrorCode": "400",
    "ResourceErrorMessage": {
      "code": 400,
      "errors": [{
        "domain": "global",
        "message": "Invalid value for field 'resource.disks[0].initializeParams.diskType': 'pd-ssd'. The URL is malformed.",
        "reason":"invalid"}],
      "message":"Invalid value for field 'resource.disks[0].initializeParams.diskType': 'pd-ssd'. The
     URL is malformed.",
      "statusMessage": "Bad Request",
      "requestPath": "https://compute.googleapis.com/compute/v1/projects/<project_id>/zones/europe-west2-a/instances",
      "httpMethod": "POST"}
    }"
```
_(It looks like I need to pass the full URL for the diskType, specific for the project maybe)_

**Comment by rick-pri** [comment]
> Array of disks associated with this instance. Persistent disks must be created before you can assign them.

I don't really understand this from the schema description.

**Comment by rick-pri** [comment]
I added a `disk.py` to build a disk resource but the way that the disks are set up for the instance it doesn't seem to make the root disk the first disk, it seems to be an either root or other disks which might be how you set up the root disk?

**Comment by rick-pri** [comment]
Okay, so, there's no separate `disk.py` resource and this seems to be required to create the disk resource to attach.  I have built one of these myself.  I can now successfully provision an instance and pass a disk or disk resources in the disks key array.

**Comment by rick-pri** [comment]
There's something weird with disk creation.  The following works without it trying to delete the root disk on the next run.
```
  - path: templates/cft-instance.py
    name: instance.py

  - name: ew2a-db-01
    type: instance.py
    properties:
      zone: 'europe-west2-a'
      #diskImage: 'projects/freebsd-org-cloud-dev/global/images/freebsd-12-1-release-amd64'
      #machineType: 'n2-standard-1'
      #diskType: 'pd-ssd'
      networks:
        - network: 'primarysite-test'
          subnetwork: '$(ref.db.selfLink)'
      disks:
        - deviceName: 'ew2a-db-01'
          initializeParams:
            sourceImage: 'projects/freebsd-org-cloud-dev/global/images/freebsd-12-1-release-amd64'
            diskType: 'zones/europe-west2-a/diskTypes/pd-ssd'  # #614 PR
            diskSizeGb: 22
          autoDelete: true
          boot: true
      tags:
        items:
          - 'grp-01'
```
