### ISSUE TITLE
[DM] Required property "zone" missing error when deploying regional gke cluster

### ISSUE THREAD

**Issue by Jensdevloo** [GoogleCloudPlatform/cloud-foundation-toolkit#664]
I want to deploy a regional GKE cluster that spans two zones in the `europe-west1` cluster.

I adapted the following template to match my needs: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/dm/templates/gke/examples/gke_regional.yaml

When deploying this template I get the following error indicating I am missing a zone parameter, although this is a regional cluster spec where the two zones I want to span are provided via the `locations` in `cluster` property.

Am I missing something here or is this a bug with the regional clusters?

Full error:
```
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1588258830750-5a483536b113a-e670caaa-b80e1d29]: errors:
- code: CONDITION_NOT_MET
  location: /deployments/gke-setup/resources/gke-prod->$.properties
  message: |
    error: object has missing required properties (["zone"])
        level: "error"
        schema: {"loadingURI":"#","pointer":"/create"}
        instance: {"pointer":""}
        domain: "validation"
        keyword: "properties"
        required: ["zone"]
        missing: ["zone"]
Makefile:5: recipe for target 'gke-setup' failed
```

Expanded config of the DM:
```
resources:
- name: gke-prod
  properties:
    cluster:
      addonsConfig:
        horizontalPodAutoscaling:
          disabled: false
        httpLoadBalancing:
          disabled: false
        istioConfig:
          disabled: false
      description: production gke cluster
      initialClusterVersion: 1.15.11-gke.9
      initialNodeCount: 2
      locations:
      - europe-west1-b
      - europe-west1-d
      maintenancePolicy:
        window:
          recurringWindow:
            recurrence: FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU
            window:
              endTime: '2020-04-26 04:00:00'
              startTime: '2020-04-26 00:00:00'
      name: gke-prod
      network: $(ref.vpc1.selfLink)
      nodePools:
      - config:
          diskSizeGb: 100
          machineType: n1-standard-2
          management:
            autoRepair: true
            autoUpgrade: true
          oauthScopes:
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring
        name: pool1
      subnetwork: $(ref.vpc1-subnet1.selfLink)
    clusterLocationType: Regional
    region: europe-west1
  type: container.v1.cluster
  metadata:
    dependsOn:
    - vpc1
    - vpc1-subnet1
```

Thanks!

**Comment by Jensdevloo** [comment]
Issue has been resolved by 
- setting the correct recource type: `type: gcp-types/container-v1beta1:projects.locations.clusters` 
- setting properties.parent: `parent: projects/{{ properties['project_id'] }}/locations/europe-west1` instead of the region
- putting initialNodeCount in the nodepool

Full jinja:
```
resources:
- name: {{ env["name"] }}
  type: gcp-types/container-v1beta1:projects.locations.clusters
  properties:
    parent: projects/{{ properties['project_id'] }}/locations/europe-west1
    cluster:
      name: {{ env["name"] }}
      description: production gke cluster
      addonsConfig:
        httpLoadBalancing:
          disabled: false
        horizontalPodAutoscaling:
          disabled: false
        istioConfig:
          disabled: false
      maintenancePolicy: 
        window:
          recurringWindow:
            window:
              startTime: "2020-04-26T00:00:00.000000000Z"
              endTime: "2020-04-26T04:00:00.000000000Z"
            recurrence: FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU
      network: {{ properties['network'] }}
      subnetwork: {{ properties['subnetwork'] }}
      nodePools:
        - name: pool1
          initialNodeCount: {{ properties['initialNodeCount'] }}
          config:
            machineType: {{ properties['machineType'] }}
            diskSizeGb: 100
            oauthScopes:
              - https://www.googleapis.com/auth/cloud-platform
          management:
            autoUpgrade: True
            autoRepair: True
      locations:
        - europe-west1-b
        - europe-west1-d
```
