### ISSUE TITLE
An issue of roleId pattern at iam_custom_role

### ISSUE THREAD

**Issue by doniz** [GoogleCloudPlatform/cloud-foundation-toolkit#733]
In the following references you'll see the patterns of schema's. It must support underscore as well `_`. So final version should be:

```
  roleId:
    type: string
    pattern: ^[a-zA-Z][0-9a-zA-Z_]{7,63}$
    description: |
      A unique ID of the custom role.
```

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/886d4c610e155a650a58444c0c7c2b90ba5a7cc3/dm/templates/iam_custom_role/organization_custom_role.py.schema#L57

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/886d4c610e155a650a58444c0c7c2b90ba5a7cc3/dm/templates/iam_custom_role/project_custom_role.py.schema#L54
