### ISSUE TITLE
More than one alerting policy causes "Too many concurrent edits" error

### ISSUE THREAD

**Issue by aahventures** [GoogleCloudPlatform/cloud-foundation-toolkit#787]
Trying to use the [Stackdriver notification channels template](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates/stackdriver_notification_channels) is fine with one alerting policy, but when used with more than one–most of the time–an error is returned:
> Too many concurrent edits to the project configuration. Please try again.

This happens on deletes also. Not sure if the template could be rewritten in such a way that this does not happen or if this is a Deployment Manager issue. If so I can refile there.

## Full Error
```
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [REDACTED]: errors:
- code: RESOURCE_ERROR
  location: /deployments/[REDACTED]/resources/alerting-policy-my-notification-channels-1
  message: '{"ResourceType":"gcp-types/monitoring-v3:projects.alertPolicies","ResourceErrorCode":"409","ResourceErrorMessage":{"code":409,"message":"Too
    many concurrent edits to the project configuration. Please try again.","status":"ABORTED","statusMessage":"Conflict","requestPath":"https://monitoring.googleapis.com/v3/projects/[REDACTED]/alertPolicies","httpMethod":"POST"}}'
```

## Reproducible with
```
imports:
  - path: templates/stackdriver_notification_channels/stackdriver_notification_channels.py
    name: stackdriver_notification_channels.py

resources:
  - name: my-notification-channels
    type: stackdriver_notification_channels.py
    properties:
      notificationChannels:
        - displayName: user@example.com
          typeName: email
          labels:
            email_address: user@example.com
      policies:
        - name: Logging health
          documentationContent: Investigate.
          conditions:
            - displayName: No logs ingested
              filter: metric.type="logging.googleapis.com/billing/bytes_ingested"
                resource.type="global"
              comparison: COMPARISON_LT
              thresholdValue: 100000
              duration: 0s
              trigger:
                count: 1
              aggregations:
                - alignmentPeriod: 1800s
                  perSeriesAligner: ALIGN_MEAN
                  crossSeriesReducer: REDUCE_SUM
        - name: Monitoring health
          documentationContent: Investigate.
          conditions:
            - displayName: Less than one time series
              filter: metric.type="monitoring.googleapis.com/stats/num_time_series"
                resource.type="global"
              comparison: COMPARISON_LT
              thresholdValue: 1
              duration: 0s
              trigger:
                count: 1
              aggregations:
                - alignmentPeriod: 1800s
                  perSeriesAligner: ALIGN_MIN
```

 #432
