### ISSUE TITLE
BigQuery table schema doesn't allow nested columns

### ISSUE THREAD

**Issue by heiantti** [GoogleCloudPlatform/cloud-foundation-toolkit#809]
Specifying a nested column in a table schema like in the following configuration:

```
imports:
  - path: templates/bigquery_table.py
    name: bigquery_table.py

- name: company__raw
    type: bigquery_table.py
    properties:
      name: company__raw
      datasetId: staging
      schema:
        - name: id
          type: STRING
          mode: REQUIRED
        - name: company_domain
          type: STRING
          mode: REQUIRED
        - name: etl_timestamp
          type: TIMESTAMP
          mode: REQUIRED
        - name: type
          type: STRING
          mode: REQUIRED
        - name: attributes
          type: RECORD
          mode: NULLABLE
          fields:
            - name: domain
              type: STRING
              mode: NULLABLE
            - name: company_name
              type: STRING
              mode: NULLABLE
```

gives the following error when trying to create or update:
> Manifest expansion encountered the following errors: Invalid properties for 'bigquery_table.py':
>     Additional properties are not allowed ('fields' was unexpected) at ['schema', 4]
> 

The bigquery_table.py.schema should allow defining the schema for nested columns as defined in the  documentation: [https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableSchema](url)

**Comment by brunoliberal** [comment]
Changing `additionalProperties` to `true` at https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/9196bdb756074dc8cb54c9b5d053de6acaffbed4/dm/templates/bigquery/bigquery_table.py.schema#L442 fix the issue but allow users to add invalid properties.

Is there a way to add a property that contains another property as type? eg.:
```
properties:
  parent:
    type: object
    properties:
      child:
        type: parent
```
